# Generated by Django 5.2.4 on 2025-08-21 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='answer',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatrecord',
            old_name='query',
            new_name='user_message',
        ),
        migrations.RenameField(
            model_name='uploadrecord',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='chatrecord',
            name='has_image',
        ),
        migrations.RemoveField(
            model_name='chatrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='active',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
