# Generated by Django 5.2.4 on 2025-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_answer_chatrecord_bot_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('patterns', models.JSONField(default=list)),
                ('response', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
