# Generated by Django 5.2.4 on 2025-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
