# Generated by Django 5.2.4 on 2025-08-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intent',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='intent',
            name='patterns',
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
