# Generated by Django 5.2.4 on 2025-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_tag_intent_name_remove_intent_patterns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.AddField(
            model_name='intent',
            name='keywords',
            field=models.CharField(default='default_keyword', max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
