name: Finnect CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: finnect_db
          POSTGRES_USER: finnect_user
          POSTGRES_PASSWORD: finnect_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U finnect_user -d finnect_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          POSTGRES_DB: finnect_db
          POSTGRES_USER: finnect_user
          POSTGRES_PASSWORD: finnect_pass
          POSTGRES_HOST: localhost
        run: |
          cd backend
          python manage.py migrate

      - name: Run tests
        run: |
          pytest

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/finnect:latest .

      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/finnect:latest
